### ISSUE TITLE
Question: OPUS encoding in iOS

### ISSUE THREAD

**Issue by eerimoq** [alta/swift-opus#35]
Hi!

Do you guys know if iOS has builtin support for converting PCM to OPUS nowdays? AVAssetWriter and AVAssetWriterInput can do it when writing to file, but I haven't been able to using AVAudioConverter for live streaming.

**Comment by ondrejkorol** [comment]
Hi @eerimoq,

did you find a solution to live streaming and compressing PCM audio buffer? I'd appreciate any help!

Cheers,

Ondrej

**Comment by eerimoq** [comment]
Paused the work before got it to work. Some ideas here: <https://github.com/eerimoq/moblin/blob/main/Moblin/HaishinKit/Codec/AudioCodecOutputSettings.swift#L63-L78>

There are more OPUS codec stuff in that repo, but nothing has been confirmed to work. Let me know it you get it working.
