### ISSUE TITLE
Consider making Opus.Application Sendable for Swift 6

### ISSUE THREAD

**Issue by msdrigg** [alta/swift-opus#36]
Hi Alta,

Lovely work on this project! I also use this project in my Roam application. I am seeing a swift 6-related error in this project as well due to the fact that Opus.Application isn't sendable. I would be happy to send in a PR for this if you are amenable.

**Comment by ydnar** [comment]
Thanks! Happy to review a PR.

**Comment by msdrigg** [comment]
Excellent and thank you @ydnar. It ended up being a 1-word change haha
