### ISSUE TITLE
Question: OPUS_INVALID_PACKET (-4) when trying to decode Opus data

### ISSUE THREAD

**Issue by Dario-GoldenSpear** [alta/swift-opus#4]
Hi,

I have been trying to decode an Opus (raw, no ogg) file using the following code:

```Swift
    private func decodeOpus() {
        do {

            guard let opusFormat = AVAudioFormat(opusPCMFormat: .float32, sampleRate: .opus48khz, channels: 1) else {
                print("unable to create opusFormat")
                return
            }

            let opusDecoder = try Opus.Decoder(format: opusFormat)
            let dataFromFile = Utilities.dataFromAudioFile(filename: "short-heartbeat-fullraw", fileExtension: "opus")!

            let decodedData = try opusDecoder.decode(dataFromFile)
            print("decoded from opus")
        } catch {
            // couldn't load file
            self.statusLabel.text = "Unable to decode audio file, error: \(error.localizedDescription)"
        }
    }
 ```
 
 I always get the mentioned error code: `OPUS_INVALID_PACKET` in this code:
 ```C
 int opus_packet_get_nb_samples(const unsigned char packet[], opus_int32 len,
      opus_int32 Fs)
{
   int samples;
   int count = opus_packet_get_nb_frames(packet, len);

   if (count<0)
      return count;

   samples = count*opus_packet_get_samples_per_frame(packet, Fs);
   /* Can't have more than 120 ms */
   if (samples*25 > Fs*3)   // --> THIS IS ALWAYS TRUE 
      return OPUS_INVALID_PACKET;
   else
      return samples;
}
 ```
 
the input file is 14542 bytes, these are the values when calling that method:
 len	opus_int32	14542
Fs	opus_int32	48000
samples	int	46080
count	int	48

I assume there is something wrong in the way I use the decoder.

QUESTIONS:
Should I divide the input data into smaller chunks and call the decoder several times? 
Could you point to a sample piece of code that shows how to configure and call the decoder?

Thanks in advance.

**Comment by ydnar** [comment]
You'll need to parse the packets out and individually pass them to the decoder. It parses a single Opus packet at a time.

**Comment by ydnar** [comment]
That said: this repo should have some examples (and tests) for the encoder and decoder. Noted.

**Comment by Dario-GoldenSpear** [comment]
Sounds good. Thanks @ydnar for the quick reply, and for putting the effort in creating this Swift wrapper as well 👌 .
