### ISSUE TITLE
Create Release so it can be imported via SPM

### ISSUE THREAD

**Issue by Reiszecke** [alta/swift-opus#6]
SPM expects a release in semantic versioning in order to be able to import. I'd PR but that isn't possible with releases 

![image](https://user-images.githubusercontent.com/11237541/130046336-d30f5d83-fc1d-43dc-ab4b-1b2054482291.png)

https://github.com/Reiszecke/swift-opus/releases/tag/1.0.0

**Comment by ydnar** [comment]
Sure, I’ll take a look.

**Comment by ydnar** [comment]
Just cut a 0.0.1 release. Let me know if this works!

**Comment by Reiszecke** [comment]
Works, thanks!
